core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import DepartamentoListView, Home, HomeSinPrivilegios

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name="core/login.html"), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name="core/login.html"), name='logout'),
    path('', Home.as_view(), name='home'),
    path('NoPermitido/', HomeSinPrivilegios.as_view(), name='sin_privilegios'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('escuelas/', include('escuela.urls')),
    path('comite/', include('comite.urls')),
    path('perfil/', include('perfil.urls')),
    path('', include('planificacion.urls')),
]

core/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.


class Departamento(models.Model):
    codigo = models.CharField('Codigo', primary_key=True, unique=True, max_length=2)
    nombre = models.CharField('Nombre', max_length=100, blank=True)

    class Meta:
        verbose_name = "Departamento"
        verbose_name_plural = "Departamentos"
        db_table = 'Departamento'
        ordering = ['codigo',]

    def asignar_codigo(self):
        new_codigo = str(self.codigo)
        # Verificamos que el codigo sea de un digito para agregar el 0
        if len(self.codigo) < 2:
            new_codigo = ('0' + str(self.codigo))
        self.codigo = new_codigo

    def __str__(self):
        return '%s' %  (self.nombre)

    def save(self, *args, **kwargs):
        self.asignar_codigo()
        super(Departamento, self).save(*args, **kwargs)

class Municipio(models.Model):
    codigo = models.CharField('Codigo', primary_key=True, unique=True, max_length=4)
    nombre = models.CharField(max_length=100)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, verbose_name='Departamento')

    class Meta:
        verbose_name = "Municipio"
        verbose_name_plural = "Municipios"
        db_table = 'Municipio'
        ordering = ['codigo',]

    def asignar_id_departamento(self):
        id_depto = '0'
        new_codigo = self.codigo
        id_depto = str(self.departamento.codigo)
        # Verificamos que el codigo sea de un digito para agregar el 0
        if len(self.codigo) < 2:
            new_codigo = ('0' + new_codigo)
            print('El caracter tiene menos de dos letras')
        # Obtenemos el codigo ingresado y lo concatenamos al del depto
        new_codigo = str(id_depto + new_codigo)
        # Lo guardamos como el codigo
        self.codigo = new_codigo

    def __str__(self):
        return '%s' % (self.nombre)

    def clean(self, **kwargs):
        super(Municipio, self).clean()
        if len(self.codigo) < 3:
            pass
        else:
            raise ValidationError('Ingrese un codigo valido')

    def save(self, *args, **kwargs):
        self.asignar_id_departamento()
        super(Municipio, self).save(*args, **kwargs)

class PersonaBase(models.Model):
    dpi = models.CharField('DPI', max_length=15, primary_key=True, unique=True)
    nombres = models.CharField('Nombres', max_length=200)
    apellidos = models.CharField('Apellidos', max_length=200)
    fecha_nac = models.DateField('Fecha de Nacimiento', blank=True, null=True)
    direccion = models.CharField('Dirección', max_length=200, blank=True, null=True)

    class Meta:
        verbose_name = "PersonaBase"
        verbose_name_plural = "PersonaBases"
        abstract = True

    def nombre_completo(self):
        return '%s %s' % (self.nombres, self.apellidos)

    def __str__(self):
        return nombre_completo()

escuela/models.py
from django.db import models
from django.db import connection

# Importamos la libreria para random
import random

from core.models import Departamento, Municipio
import datetime

# Create your models here.

# Creacion de un
def get_rand_string():
    """Devuelve un string de 10 caracteres aleatorios"""
    return ''.join(random.choice(
            'abcdefghijklmnopqrstuvwxyz') for i in
            range(3)) + ''.join(random.choice(
            '0123456789') for i in
            range(3))

class Escuela(models.Model):
    codigo = models.CharField('Codigo', primary_key=True, unique=True, max_length=10, default=get_rand_string)
    nombre = models.CharField('Nombre', max_length=200)
    direccion = models.CharField('Direccion', max_length=200)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, verbose_name='Departamento')
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE, verbose_name='Municipio')
    fecha_crea = models.DateField('Fecha', auto_now_add=True)

    class Meta:
        verbose_name = "Escuela"
        verbose_name_plural = "Escuelas"
        db_table = 'Escuela'

    # Llamamos a una funcion en la base de datos, y evaluamos si existe un Usuario
    def existe_usuario_sql(self):
        # dato = 0
        result = False
        # with connection.cursor() as cursor:
        #     dato = cursor.callfunc("FN_GET_USUARIO", int, [self.codigo])
        # # Segun el procedimiento creado si retorna 0 es que existe uno o mas comites
        from perfil.models import UsuarioEscuela
        if UsuarioEscuela.objects.filter(escuela=self.codigo).exists():
            result = True
        else:
            result = False
        return result

    # Llamamos a una funcion en la base de datos, y evaluamos si existe un comite
    def existe_fondo_sql(self):
        dato = 0
        year = datetime.date.today().year
        int(year)
        result = False
        from comite.models import Fondo
        for f in Fondo.objects.fiter(ciclo=year):
            if f.comite.escuela == self.codigo:
                dato = dato + 1
        # with connection.cursor() as cursor:
        #     dato = cursor.callfunc("FN_GET_FONDO", int, [self.codigo])
        # Segun el procedimiento creado si retorna 0 es que existe uno o mas comites
        if  dato >= 1:
            result = True
        else:
            result = False
        return result


    def asignar_numeracion(self):
        new_id = ''
        new_id = (str(self.municipio.codigo)+self.codigo.upper())
        for escuela in Escuela.objects.all():
            if escuela.codigo == self.codigo:
                self.codigo= escuela.codigo
            else:
                self.codigo = new_id

    def __str__(self):
        return '%s' % (self.nombre)

    def clean(self, **kwargs):
        super(Escuela, self).clean()
        self.nombre = self.nombre.upper()
        self.direccion = self.direccion.upper()
        n1 = self.municipio.codigo
        n2 = self.codigo
        if len(n2)>6:
            n3 = n2[4:]
            self.codigo = (str(n1)+str(n3)).upper()
        else:
            self.codigo = (str(n1)+str(n2)).upper()

    '''
    def save(self, *args, **kwargs):
        self.asignar_numeracion()
        super(Escuela, self).save(*args, **kwargs)
    '''


class Comite(models.Model):
    nombre = models.CharField('Nombre', max_length=200)
    descripcion = models.TextField('Descripcion')
    fecha_crea = models.DateField("Fecha Creacion", auto_now_add=True)
    escuela = models.OneToOneField(Escuela, on_delete=models.CASCADE, verbose_name='Escuela')

    class Meta:
        verbose_name = "Comite"
        verbose_name_plural = "Comites"
        db_table = 'Comite'

    def saldo(self):
        from comite.models import Fondo
        fondo = Fondo.objects.filter(comite=self.pk).get()
        return '%s' % (fondo.saldo)

    def __str__(self):
        return '%s' % (self.nombre)

    def clean(self, **kwargs):
        super(Comite, self).clean()
        self.nombre = self.nombre.upper()
        self.descripcion = self.descripcion.upper()

planificacion/models.py
from django.db import models

# Importamos pra la conecxion a la BD
from django.db import connection

from django.core.exceptions import ValidationError

from comite.models import Comite, Fondo

# Create your models here.

class Planificacion(models.Model):
    comite = models.ForeignKey(Comite, on_delete=models.CASCADE, verbose_name='Comite')
    descripcion = models.TextField('Descripcion')
    fecha_crea = models.DateField("Fecha Creacion", auto_now_add=True)
    ciclo = models.PositiveSmallIntegerField('Ciclo')

    class Meta:
        ordering = ['-ciclo']
        unique_together = ['comite', 'ciclo']
        verbose_name = "Planificacion"
        verbose_name_plural = "Planificaciones"
        db_table = 'Planificacion'

    def actividades_registradas(self):
        valor = 0
        for a in Actividad.objects.all():
            if a.plainficacion == self.id:
                valor = valor+1
        return valor

    def actividades_finalizadas(self):
        valor = 0
        for a in Actividad.objects.all():
            if a.plainficacion == self.id:
                if a.estado == 0:
                    valor = valor+1
        return valor

    def actividades_aprobadas(self):
        valor = 0
        for a in Actividad.objects.all():
            if a.plainficacion == self.id:
                if a.estado == 1:
                    valor = valor+1
        return valor

    def llamar_saldo(self):
        saldo = Fondo.objects.filter(comite=self.comite, ciclo=self.ciclo).get()
        return saldo.saldo

    def __str__(self):
        return 'Ciclo: %s, %s' % (self.ciclo, self.comite)

ACTIVIDAD_CHOICES = [
    ('Deportiva', 'Deportiva'),
    ('Cultural', 'Cultural'),
    ('Social', 'Social'),
    ('Artistica', 'Artistica'),
    ('Academica', 'Academica'),
]

class Actividad(models.Model):
    tipo = models.CharField('Tipo de Actividad', choices=ACTIVIDAD_CHOICES, max_length=25)
    descripcion = models.TextField('Descripcion')
    fecha_prog = models.DateField('Fecha Programada')
    costo = models.DecimalField('Costo', max_digits=10, decimal_places=2)
    estado = models.PositiveSmallIntegerField('Estado', default=2)
    fecha_crea = models.DateField("Fecha Creacion", auto_now_add=True)
    plainficacion = models.ForeignKey(Planificacion, on_delete=models.CASCADE, verbose_name='Comite')

    class Meta:
        verbose_name = "Actividad"
        verbose_name_plural = "Actividads"
        db_table = 'Actividad'

    def costo_real(self):
        saldo = 0
        for pago in PagoActividad.objects.filter(actividad=self.id):
            saldo = pago.valor+saldo
        saldo = float(saldo)
        return saldo

    def estado_actividad(self):
        if self.estado == 0:
            return 'Finalizada'
        elif self.estado == 1:
            return 'Autorizada'
        elif self.estado == 2:
            return 'Ingresada'

    def __str__(self):
        return '%s %s' % (self.plainficacion.ciclo, self.descripcion)

def comite_directory_path(instance, filename):
    return 'Actividad/' + filename

class PagoActividad(models.Model):
    actividad = models.ForeignKey(Actividad, on_delete=models.CASCADE, verbose_name='Actividad')
    factura = models.FileField(upload_to='uploads/', blank=True)
    valor = models.DecimalField('Costo', max_digits=10, decimal_places=2)
    descripcion = models.TextField('Descripcion')
    fecha_crea = models.DateField("Fecha Creacion", auto_now_add=True)

    class Meta:
        db_table = 'PagoActividad'
        verbose_name = "PagoActividad"
        verbose_name_plural = "PagoActividades"

    def validar_retiro_sql(self):
        ciclo = self.actividad.plainficacion.ciclo
        comite = self.actividad.plainficacion.comite
        fondo = Fondo.objects.filter(comite=comite, ciclo=ciclo).get()
        saldo = fondo.saldo
        dato = 0
        result = False
        #with connection.cursor() as cursor:
        #    dato = cursor.callfunc("VALIDAR_PAGO_ACTIVIDAD", int, [saldo, self.valor, fondo.pk])
        # Segun el procedimiento creado si retorna 0 es que existe uno o mas comites
        if  saldo < self.valor:
            result = True
        else:
            result = False
        return result

    def __str__(self):
        return 'Costo: %s, fecha_crea: %s' % (
            self.valor, self.fecha_crea
            )

    def clean(self, **kwargs):
        super(PagoActividad, self).clean()
        # Si nos retorna verdadero lanzamos un error
        respuestaSQL_Retiro = self.validar_retiro_sql()
        if respuestaSQL_Retiro is True:
            raise ValidationError('No se Cuenta con Suficiente Saldo')

core/views.py
from django.shortcuts import render
from django.utils import timezone

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, \
PermissionRequiredMixin

from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from .models import Departamento, Municipio
from escuela.models import Escuela

# Create your views here.

class Home(LoginRequiredMixin, TemplateView):
    login_url = 'login'
    template_name = "core/home.html"

class HomeSinPrivilegios(TemplateView):
    template_name = "core/sin_privilegios.html"

class SinPrivilegios(LoginRequiredMixin, PermissionRequiredMixin):
    login_url = 'login'
    raise_exception=False
    redirect_field_name="redirect_to"

    def handle_no_permission(self):
        from django.contrib.auth.models import AnonymousUser
        if not self.request.user==AnonymousUser():
            self.login_url='sin_privilegios'
        return HttpResponseRedirect(reverse_lazy(self.login_url))

class DepartamentoListView(ListView):
    model = Departamento
    template_name = "core/prueba.html"

    def get_context_data(self, **kwargs):
        municipio = Municipio.objects.all()
        escuela = Escuela.objects.all()
        departamento = Departamento.objects.all()
        return {
        	'departamento': departamento, 'municipio': municipio,
        	'escuela': escuela
        	}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title> MINEDUC |{% block title %}{% endblock %}</title>
        <link  rel="icon"   href="{% static 'core/img/logo_gt1.png' %}" type="image/png" />
        <!-- Carga de Bootstrap-->
        <link rel="stylesheet" href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}">

        <!-- Fuentes -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'core/vendor/octicons/package/build/build.css' %}" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'core/vendor/font-kp/fonts/style.css' %}">

        <!-- Fuente Libre Baskerville-->
        <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville&display=swap" rel="stylesheet">

        <!-- Mis CSS -->
        <link rel="stylesheet" href="{% static "core/css/mineduc.css" %}">

        <!-- DataTable -->
        <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">

        <!-- JQuery Confirm -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

        <!-- Load ExtraFiles -->
        {% block load_files %}
        {% endblock load_files %}

        <style>
            #logout_a{
                color: #A50303;
                font-weight: bold;
            }
            #logout_a:hover{
                color: #FF2D2D;
                text-decoration: none;
            }
        </style>

</head>
<body>
    {% block body %}
    <!--navbar-->
    <!-- Image and text -->
    <div class="navbar navbar-light d-flex justify-content-around bandera">
        <div class="">
            <img src="{% static 'core/img/logo_mineduc.html' %}" width="150" alt="">
            <!--img src="{% static 'core/img/logo_mineduc.html' %}" width="120" alt=""-->
        </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container ">
            <a class="navbar-brand {% if request.path == '/' %}
                        text-primary
                    {% endif %}" href="{% url 'home' %}">
                <span class="fas fa-home mr-2"></span>Home
            </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto text-uppercase">

                {% if perms.escuela.view_escuela %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/escuelas/list/' %} text-primary {% endif %}" href="{% url 'list_escuela' %}">
                            <span class="fas fa-school mr-2"></span>Escuelas <span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}

                {% if perms.escuela.view_comite %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/comite/' %} text-primary {% endif %}" {% if request.user.groups.all.0.name == "USUARIOCOMITE" %} href="{% url 'comite_usuario' %}" {% else %} href="{% url 'comite' %}" {% endif %}>
                            <span class="fas fa-users mr-2"></span>
                            Comite
                        </a>
                    </li>
                {% endif %}

                {% if perms.planificacion.view_planificacion %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/planificacion/' %} text-primary {% endif %}" href="{% url 'planificacion' %}">
                        <span class="fas fa-list-alt mr-2"></span>
                        Planificacion
                    </a>
                </li>
                {% endif %}

              <!--li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li-->
            </ul>

          </div>
          <div class="ml-auto">
              <a id="logout_a" href="{% url 'logout' %}"><span class="fas fa-power-off"></span> Salir</a>
          </div>
      </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <!-- Creacion de Modal Popup -->
    <div class="modal fade" id="popup"></div>
    {% endblock body %}

    <!--Scripts-->
    <script src="{% static 'core/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/js/main.js' %}"></script>

    <!-- DataTable -->
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

    <!-- JQuery Confirm -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

    <!-- JQuery Mask CDN -->
    <script src="{% static 'core/vendor/jQuery-Mask-Plugin-master/dist/jquery.mask.js' %}"></script>
    <script src="{% static 'core/vendor/jQuery-Mask-Plugin-master/dist/jquery.mask.min.js' %}"></script>

    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script>
            // Pasamos el ID del Plan
            var id_plan
            $('.addActividad').click(function(event) {
                /* Act on the event */
                event.preventDefault();
                id_plan = $(this).attr("data-p");
            });

            // Pasar el id del comite al agregar integrante
            $('#addIntegrante').click(function(event) {
                /* Act on the event */
                id_comite = $(this).attr("data-comite");
            });

            // Pasar el id del comite al agregar usuario
            $('#addComiteUser').click(function(event) {
                /* Act on the event */
                id_comite = $('#addIntegrante').attr("data-comite");
            });

            // Pasar el id del comite al asignar un fondo
            $('#asignarFondo').click(function(event) {
                /* Act on the event */
                id_fondo = $('#fondo_span').attr("data-pk");
            });

            // Pasar el id de la Escuela al agregar usuario
            $('.add_user').click(function(event) {
                addUserIdEscuela = $(this).attr("data-escuela");
            });
            function mensaje(title='', msg, color='green'){
                $.alert({
                    title:title,
                    theme: 'material',
                    type: color,
                    content:msg
                });
            };
    </script>

    {% block js_block %}
    {% endblock js_block %}

    {% block control_modal %}
        <script>

            // Funcion para abrir modal y no se cierre al dar click
            function abrir_modal(url)
            {
                $("#popup").load(url, function(){
                    $(this).modal({
                        backdrop: 'static',
                        keyboard: false
                    });
                    $(this).modal('show');
                });
                return false;
            };

            // Funcion para cerrar modal
            function cerrar_modal(url)
            {
                $('#popup').modal('hide');
                return false;
            };
        </script>
    {% endblock control_modal %}
</body>
<footer class="foot d-flex justify-content-center fixed-bottom pt-2">
    <p>Create By: KodePrint - <img src="{% static "core/img/kp_white.png" %}" width="25"> &copy; 2020</p>
</footer>
</html>

core/templates/core/home.html
{% extends "core/base.html" %}

{% block title %}
	Home
{% endblock title %}

{% block content %}
<div class="container mb-4">
	<div class="row">

		<div class="container d-flex">
			<div class="izquierda col-6 p-4">
				<div class="row arriba">
					<div class="card border-secondary mb-3" style="min-height: 16rem;">
						<div class="card-header">
							<h5 class="text-uppercase">Bienvenido</h5>
						</div>
						<div class="card-body text-secondary">
						    <small class="text-justify">Esta es la sección principal de esta aplicación web en donde encontraras información relevante sobre el funcionamiento de la misma, la aplicación cuenta con 3 tipos de usuarios los cuales son:</small>
							<small>
								<ul class="text-uppercase">
									<b>
										<li class="text-warning">Mineduc</li>
										<li class="text-info">Escuelas</li>
										<li class="text-success">Comite</li>
									</b>
								</ul>
							</small>
						</div>
					</div>
				</div>
				<div class="row abajo">
					<div class="card border-info" style="min-height: 16rem;">
						<div class="card-header">
							<h5 class="text-uppercase text-info"><b>Escuelas</b></h5>
						</div>
						<div class="card-body text-info">
						    <b>
						    	<small>
						    		<p class="text-justify">Las escuelas se encargarán del registro del comité y sus integrantes, realizando de esta manera el registro de los padres de familia y puestos que tendrán en el comité.</p>
						    		<p class="text-justify">De la misma manera registraran el fondo o dinero que fue asignado a cada comité, esta asignación es una por año. Solamente podrá verificar como ha sido el movimiento de los fondos que en un principio asignaron obteniendo un documento el cual presentara los distintos movimientos realizados.</p>
						    	</small>
						    </b>
						</div>
					</div>
				</div>
			</div>
			<div class="derecha col-6 p-4">
				<div class="row arriba">
					<div class="card border-warning mb-3" style="min-height: 16rem;">
					  <div class="card-header">
					  	<h5 class="text-uppercase text-warning"><b>Mineduc</b></h5>
					  </div>
					  	<div class="card-body text-warning">
							<b>
								<small>
									<p class="text-justify">La función de este usuario es el gestionar las escuelas dígase la creación, la modificación o la eliminación de las escuelas en el sistema.</p>
									<p class="text-justify">Así mismo luego de crear una escuela se podrá crear un usuario para que cada escuela tenga acceso a la aplicación, ya que las escuelas tienen otros roles y funciones dentro de esta.</p>
								</small>
							</b>
					  	</div>
					</div>
				</div>
				<div class="row abajo">
					<div class="card border-success" style="min-height: 16rem;">
					  <div class="card-header">
					  	<h5 class="text-uppercase text-success"><b>Comite</b></h5>
					  </div>
					  	<div class="card-body text-success">
							<b>
								<small>
									<p class="text-justify">En cuanto al comité este deberá ingresar su plan anual de actividades, en el que se debe detallar como será invertido el fondo, cada inversión debe ser justificada por medio de facturas que deberán ser ingresadas al sistema.</p>
									<p class="text-justify">Por lo que se tendrá el control de gastos y cada actividad que se apruebe por el comité reflejara un movimiento en el fondo del mismo.</p>
								</small>
							</b>
					  	</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container mb-4">
			<hr>
			<small class="text-justify mb-4"><b>Esta aplicación esta desarrollada para ser usada en una pantalla grande por lo que se recomienda utilizar un computador para acceder a la aplicación y de esta manera obtener la mejor experiencia para el usuario</b></small>
			<hr>
		</div>

	</div>
</div>
{% endblock content %}

core/templates/core/prueba.html
{% extends "core/base.html" %}

{% block content %}
	<h1 class="text-primary">Esto es una prueba</h1>

	<div>
		<ul>
		{% for depto in departamento %}
		    <li>{{ depto }}</li>
		    <ul>
			    {% for muni in municipio %}
			    	{% if muni.departamento.codigo == depto.codigo %}
			    		<li>{{muni}}</li>
			    	{% endif %}
			    {% empty %}
			    	<li>No se han registrado datos</li>
			    {% endfor %}
		    </ul>
		{% empty %}
		    <li>No se han registrado datos</li>
		{% endfor %}
	</ul>
	</div>
	<hr>
	<div>
		<table>
			<caption>table title and/or explanatory text</caption>
			<thead>
				<tr>
					<th>Codigo</th>
					<th>Nombre</th>
				</tr>
			</thead>
			<tbody>
				{% for escuela in escuela %}
					<tr>
						<td>{{escuela.codigo}}</td>
						<td>{{escuela.nombre}}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock content %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Prueba</title>
	<link rel="stylesheet" href="">
</head>
<body>

</body>
</html>

core/templates/core/sin_privilegios.html
{% extends "core/base.html" %}

{% load static %}
{% block content %}

<style>
	div.card{
		border-left: 5px solid red;
		border-bottom: 3px solid red;
		box-shadow: 2px 2px 10px;
	}
</style>
	<div class="container d-flex justify-content-center mt-4">
		<div class="col-xl-6 col-md-6 mb-6">
			<div class="card shadow h-100">
				<div class="card-header">
					<div class="text-xs font-weight-bold text-primary text-uppercase m-1">
						<span class="fas fa-ban mr-2 text-danger h2"></span>El Usuario: <span class="text-danger">{{user.username}}</span>
					</div>
				</div>
				<div class="card-body">

					<div class="row alig-items-center">
						<div class="col mr-2">
							<div class="row">
								<div class="container">
									<span class="text-danger mr-1">No tiene suficientes privilegios </span> <span>para cargar la opcion solicitada.</span>
									<br>
									<small>Para poder acceder, debes loguearte con un usuario con privilegios necesarios</small>
								</div>
							</div>
							<div class="dropdown-divider"></div>

							<div class="row">
								 <div class="col d-flex justify-content-between">
								 	<a href="{% url 'home' %}" class="btn btn-success"><span class="fas fa-home mr-2"></span>Ir a Inicio</a>
								 	<a href="{% url 'login' %}" class="btn btn-warning"><span class="fas fa-sign-in-alt mr-2"></span>Ingresar con otro Usuario</a>
								 </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}