core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import DepartamentoListView, Home, HomeSinPrivilegios

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name="core/login.html"), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name="core/login.html"), name='logout'),
    path('', Home.as_view(), name='home'),
    path('NoPermitido/', HomeSinPrivilegios.as_view(), name='sin_privilegios'),
]

escuela/urls.py
from django.urls import path

from .views import EscuelaListView, EscuelaCreate, load_municipios, EscuelaDelete, EscuelaUpdate

urlpatterns = [
	path('list/', EscuelaListView.as_view(), name='list_escuela'),
	path('registrar', EscuelaCreate.as_view(), name='create_escuela'),
	path('eliminar/<slug:pk>', EscuelaDelete.as_view(), name='eliminar_escuela'),
	path('actualizar/<slug:pk>', EscuelaUpdate.as_view(), name='actualizar_escuela'),
	# Url para cargar el template municipios con ajax
	path('ajax/load_muni/', load_municipios, name='ajax_load_muni'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('escuelas/', include('escuela.urls')),
    path('comite/', include('comite.urls')),
    path('perfil/', include('perfil.urls')),
    path('', include('planificacion.urls')),
]

escuela/models.py
from django.db import models
from django.db import connection

# Importamos la libreria para random
import random

from core.models import Departamento, Municipio
import datetime

# Create your models here.

# Creacion de un
def get_rand_string():
    """Devuelve un string de 10 caracteres aleatorios"""
    return ''.join(random.choice(
            'abcdefghijklmnopqrstuvwxyz') for i in
            range(3)) + ''.join(random.choice(
            '0123456789') for i in
            range(3))

class Escuela(models.Model):
    codigo = models.CharField('Codigo', primary_key=True, unique=True, max_length=10, default=get_rand_string)
    nombre = models.CharField('Nombre', max_length=200)
    direccion = models.CharField('Direccion', max_length=200)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, verbose_name='Departamento')
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE, verbose_name='Municipio')
    fecha_crea = models.DateField('Fecha', auto_now_add=True)

    class Meta:
        verbose_name = "Escuela"
        verbose_name_plural = "Escuelas"
        db_table = 'Escuela'

    # Llamamos a una funcion en la base de datos, y evaluamos si existe un Usuario
    def existe_usuario_sql(self):
        # dato = 0
        result = False
        # with connection.cursor() as cursor:
        #     dato = cursor.callfunc("FN_GET_USUARIO", int, [self.codigo])
        # # Segun el procedimiento creado si retorna 0 es que existe uno o mas comites
        from perfil.models import UsuarioEscuela
        if UsuarioEscuela.objects.filter(escuela=self.codigo).exists():
            result = True
        else:
            result = False
        return result

    # Llamamos a una funcion en la base de datos, y evaluamos si existe un comite
    def existe_fondo_sql(self):
        dato = 0
        year = datetime.date.today().year
        int(year)
        result = False
        from comite.models import Fondo
        for f in Fondo.objects.fiter(ciclo=year):
            if f.comite.escuela == self.codigo:
                dato = dato + 1
        # with connection.cursor() as cursor:
        #     dato = cursor.callfunc("FN_GET_FONDO", int, [self.codigo])
        # Segun el procedimiento creado si retorna 0 es que existe uno o mas comites
        if  dato >= 1:
            result = True
        else:
            result = False
        return result


    def asignar_numeracion(self):
        new_id = ''
        new_id = (str(self.municipio.codigo)+self.codigo.upper())
        for escuela in Escuela.objects.all():
            if escuela.codigo == self.codigo:
                self.codigo= escuela.codigo
            else:
                self.codigo = new_id

    def __str__(self):
        return '%s' % (self.nombre)

    def clean(self, **kwargs):
        super(Escuela, self).clean()
        self.nombre = self.nombre.upper()
        self.direccion = self.direccion.upper()
        n1 = self.municipio.codigo
        n2 = self.codigo
        if len(n2)>6:
            n3 = n2[4:]
            self.codigo = (str(n1)+str(n3)).upper()
        else:
            self.codigo = (str(n1)+str(n2)).upper()

    '''
    def save(self, *args, **kwargs):
        self.asignar_numeracion()
        super(Escuela, self).save(*args, **kwargs)
    '''


class Comite(models.Model):
    nombre = models.CharField('Nombre', max_length=200)
    descripcion = models.TextField('Descripcion')
    fecha_crea = models.DateField("Fecha Creacion", auto_now_add=True)
    escuela = models.OneToOneField(Escuela, on_delete=models.CASCADE, verbose_name='Escuela')

    class Meta:
        verbose_name = "Comite"
        verbose_name_plural = "Comites"
        db_table = 'Comite'

    def saldo(self):
        from comite.models import Fondo
        fondo = Fondo.objects.filter(comite=self.pk).get()
        return '%s' % (fondo.saldo)

    def __str__(self):
        return '%s' % (self.nombre)

    def clean(self, **kwargs):
        super(Comite, self).clean()
        self.nombre = self.nombre.upper()
        self.descripcion = self.descripcion.upper()

escuela/forms.py
from django import forms
from .models import Escuela
from core.models import Municipio

from betterforms.multiform import MultiModelForm

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class EscuelaForm(forms.ModelForm):
    class Meta:
        model = Escuela
        fields = [
        	'codigo', 'nombre', 'direccion', 'departamento', 'municipio'
        	]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['municipio'].queryset = Municipio.objects.none()
        self.fields['codigo'].widget.attrs['readonly'] = True
        self.fields['codigo'].widget.attrs['display'] = None

        if 'departamento' in self.data:
        	try:
        		departamento_id = str(self.data.get('departamento'))
        		self.fields['municipio'].queryset = Municipio.objects.filter(departamento=departamento_id).order_by('codigo')
        	except (ValueError, TypeError):
        		pass


class EscuelaUpdateForm(forms.ModelForm):
    class Meta:
        model = Escuela
        fields = [
            'codigo', 'nombre', 'direccion'
            ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['codigo'].widget.attrs['readonly'] = True


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=140, required=True)
    last_name = forms.CharField(max_length=140, required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )

class EscuelaUsuarioForm(MultiModelForm):
    form_classes = {
        'escuela': EscuelaForm,
        'usuario': SignUpForm,
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if 'departamento' in self.data:
            try:
                departamento_id = int(self.data.get('departamento'))
                self.fields['municipio'].queryset = Municipio.objects.filter(departamento=departamento_id).order_by('codigo')
            except (ValueError, TypeError):
                pass

escuela/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy

from django.utils import timezone

from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView

from core.views import SinPrivilegios

from .models import Escuela
from core.models import Departamento, Municipio

from .forms import EscuelaForm, EscuelaUpdateForm, SignUpForm, EscuelaUsuarioForm

# Create your views here.

class EscuelaCreate(SinPrivilegios, CreateView):
    permission_required = ['escuela.view_escuela', 'escuela.add_escuela']
    model = Escuela
    form_class = EscuelaForm
    success_url = reverse_lazy('list_escuela')

# Listado de Escuelas
class EscuelaListView(SinPrivilegios, ListView):
    permission_required = ['escuela.view_escuela', 'escuela.add_escuela']
    model = Escuela
    context = 'list_objects'
    paginate_by = 100  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super(EscuelaListView, self).get_context_data(**kwargs)
        context.update(**kwargs)
        dato = None
        usuario = self.request.user
        context['escuela'] = Escuela.objects.all()
        context['depto'] = Departamento.objects.all()
        context['muni'] = Municipio.objects.filter(departamento=dato)
        return context

# Vista ajax para devolver los municipios
def load_municipios(request):
    departamento_id = request.GET.get('depto')
    print(departamento_id)
    municipio = Municipio.objects.filter(departamento=departamento_id).order_by('codigo')
    return render(request, 'escuela/include/municipio_dropdown_list_options.html', {'municipio': municipio})

class EscuelaDelete(SinPrivilegios, DeleteView):
    permission_required = ['escuela.view_escuela', 'escuela.add_escuela']
    model = Escuela
    success_url = reverse_lazy('list_escuela')

class EscuelaUpdate(SinPrivilegios, UpdateView):
    permission_required = ['escuela.view_escuela', 'escuela.add_escuela']
    model = Escuela
    form_class = EscuelaUpdateForm
    template_name = 'escuela/escuela_form.html'
    success_url = reverse_lazy('list_escuela')

escuela/templates/escuela/escuela_confirm_delete.html
<div class="modal-dialog shadow">
	<div class="modal-content">

		<form method="post">{% csrf_token %}
			<!-- Card Body -->
			<div class="card-body">
							<div class="row no-gutters aling-items-center">
								<div class="col mr-2">
									<div class="container">
										<div class="row">
											<p><span class="fas fa-exclamation-circle text-warning mr-2" style="font-size:26px"></span>¿Está seguro de que quiere borrar: <b>"{{ object }}"</b>?</p>
											<small><span class="text-danger">
												<span class="fas fa-exclamation text-danger mr-2"></span>Al hacer click en <b>Sí,</b> se eliminara el objeto y no se podra recuperar, asi mismo se eliminaran todos los objetos que tengan relacion con este (<b> Comites, Planificaiones, y Actividades </b>)..!
											</span></small>
										</div>
									</div>
								</div>
							</div>
			</div>

			<!-- Card Footer -->
			<div class="card-footer">
				<div class="row">
					<div class="col d-flex justify-content-between">
						<button id="delete" class="btn btn-warning text-white" value="">Sí, Estoy Seguro</button>
						<button onclick="return cerrar_modal()" type="submit" class="btn btn-danger">Cancelar</button>
					</div>
				</div>
			</div>
		</form>

	</div>

</div>

		<small class="text-danger">
			{% if form.errors %}
				{% for field in form %}
					{% if field.errors %}
						{% for error in field.errors  %}
							<p>{{field.name}} {{error|escape}}</p>
						{% endfor %}
					{% endif %}
				{% endfor %}

				{% if form.non_field_errors %}
					{% for error in field.errors  %}
							{{error|escape}}
						{% endfor %}
				{% endif %}
			{% endif%}
		</small>

	</div>
</div>

<script>

	// Eliminar con ajax una escuela
	var token = $('input[name=csrfmiddlewaretoken]').val();
	$.ajaxSetup({
		beforeSend: function(xhr, settings) {
			if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))){
				xhr.setRequestHeader("X-CSRFToken", token);
			}
		}
	});

		$("#delete").click(function(e){
			e.preventDefault();
			var id = "{{ object.pk }}";
			var template = "{% url 'eliminar_escuela' object.pk %}";
			var data = {"id":id};
			data = JSON.stringify(data);

			$.ajax({
                type: "POST",
                url: template,
                data: data,
                beforeSend: function(xhr, settings){
                	$.ajaxSettings.beforeSend(xhr, settings);
                },
                success: function(response){
                    cerrar_modal();
                    location.reload();
                },
                error: function(jqXHR, textStatus, errorThrow){
                    console.log(textStatus, errorThrow);
                    cerrar_modal();
                }
            });

		});

		/*
        $("#delete").click(function(e){
            e.preventDefault();
            //alert("Probando");
            var id = {{escuela.pk}};
            var data = {"id":id};
            data = JSON.stringify(data);
        })

            
            $.ajax({
                type: "POST",
                url: template,
                data: data,
                success: function(response){
                    console.log(response);
                    cerrar_modal();
                    alert(response);
                },
                error: function(jqXHR, textStatus, errorThrow){
                    console.log(textStatus, errorThrow);
                    cerrar_modal();
                }
            });*/
</script>

escuela/templates/escuela/escuela_form.html
{% load widget_tweaks %}
{% load static %}
<style>
	.new_add{
		border-left: 3px solid #02B012;
	}
	.edit{
		border-left: 3px solid #FF9A23;
	}
</style>
<div class="modal-dialog modal-lg shadow">
	<div class="modal-content {% if object %} edit {% else %} new_add {% endif %}">
		{% if object %}
			<form method="POST" role="form" class="form-group" action="{% url 'actualizar_escuela' escuela.pk %}" id="escuale_form" data-muni-url="{% url 'ajax_load_muni' %}" novalidate>
		{% else %}
			<form method="POST" role="form" class="form-group" action="{% url 'create_escuela'%}" id="escuale_form" data-muni-url="{% url 'ajax_load_muni' %}" novalidate>
		{% endif %}
			{%csrf_token%}
			<div class="col-xl-12 col-md-12">

				<!-- Card Header -->
				<div class="card mt-2	">
					<div class="card-header">
						<div class="tex-xs title_body {% if object %} text-warning {% else %} text-primary {% endif %} font-weight-bold text-uppercase mb-1">
							<div class="row container">
								<div>
									<span class="mr-2 fas fa-school"></span>
									{% if object %}
										Editar
									{% else %}
										Registrar
									{% endif %}
										 Escuela
								</div>
								<div class="ml-auto">
									{% if object %}
										<span class="ml-auto fas fa-plus text-warning"></span>
									{% else %}
										<span class="ml-auto fas fa-edit text-primary"></span>
									{% endif %}
								</div>
							</div>
						</div>
					</div>

					<!-- Card Body -->
					<div class="card-body">
						<div class="row no-gutters aling-items-center">
							<div class="col mr-2">
								<div class="container">
									<div class="row mb-2">
										<div class="col-12">
											<div class="form-inline">
											    {% render_field form.codigo class+="form-control" display="none" %}
											    {% render_field form.fecha_crea class+="form-control" %}
											 </div>
										</div>
									</div>

									<div class="row">
										<div class="col-12">
											<div class="form-group">
											    {% render_field form.nombre class+="form-control" placeholder="Nombre de la Escuela" autocomplete='off' %}
											 </div>
										</div>
									</div>

									<div class="row">
										<div class="col-12">
											<div class="form-group">
											    {% render_field form.direccion class+="form-control" placeholder="Dirección de la Escuela" autocomplete='off' %}
											 </div>
										</div>
									</div>

									<div class="row">
										<div class="col-6">
											<div class="form-inline">
												{% if object %}
												{% else %}
													<label id="label_depto" for="departamento" class="mr-2">Departamento: </label>
													{% render_field form.departamento class+="form-control" style="width:100%" %}
												{% endif %}
											 </div>
										</div>
										<div class="col-6">
											<div class="form-inline">
												{% if object %}
												{% else %}
													<label id="label_muni" for="municipio" class="mr-2">Municipio: </label>
											    	{% render_field form.municipio class+="form-control" style="width:100%" %}
												{% endif %}
											 </div>
										</div>
									</div>

								</div>
							</div>
						</div>
					</div>

					<!-- Card Footer -->
					<div class="card-footer">
						<div class="row">
							<div class="col d-flex justify-content-between">
								<button type="submit" class="btn btn-success" id="guardar">Guardar</button>
								<button onclick="return cerrar_modal()" type="submit" class="btn btn-danger">Cancelar</button>
							</div>
						</div>
					</div>
				</div>

			</div>
		</form>

		<small class="text-danger">
			{% if form.errors %}
				{% for field in form %}
					{% if field.errors %}
						{% for error in field.errors  %}
							<p>{{field.name}} {{error|escape}}</p>
						{% endfor %}
					{% endif %}
				{% endfor %}

				{% if form.non_field_errors %}
					{% for error in field.errors  %}
							{{error|escape}}
						{% endfor %}
				{% endif %}
			{% endif%}
		</small>

	</div>
</div>

<script>
		{% if object %}
			$("#id_codigo").hide();
			$("#guardar").click(function(event) {
				/* Act on the event */
				if(
					$("#id_nombre").val().length <= 0 ||
					$("#id_direccion").val().length <= 0
					) {
						event.preventDefault();
						alert("Existen Campos Vacios")
					}
			});
		{% else %}
			$("#id_codigo").hide();
			// Capturando el submit
			$("#guardar").click(function(event) {
				if(
					$("#id_nombre").val().length <= 0 ||
					$("#id_direccion").val().length <= 0 ||
					$("#id_departamento").val() <= 0 ||
					$("#id_municipio").val() <= 0) {
					event.preventDefault();
					$.alert({
					    title: 'Se ha encontrado un  error..!',
					    content: 'Verifique que todos los campos esten llenos..!',
					    type: 'red',
					    typeAnimated: true,
					    confirm: function(){
					        alert('Confirmed!');
					    }
					});
				}

			});

			// Capturando el change de departamento
			$("#id_departamento").change(function() {
				// Guardamos la data de la url que trae el formulario
				var muniUrl = $("#escuale_form").attr("data-muni-url");
				// Guardamos el id del departamento
				var departamentoId = $(this).val();

				// Iniciamos el metodo ajax
				$.ajax({
					url: muniUrl,
					data: {
						'depto': departamentoId
					},
					success: function (data) {
						$("#id_municipio").html(data);
						console.log(data);
					}
				});
			});
		{% endif %}
</script>

escuela/templates/escuela/escuela_list.html
{% extends "core/base.html" %}
{% load static %}

{% block load_files %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
{% endblock load_files %}

{% block content %}
<style>
    .circle-btn{
        border-radius: 25px;
    }
    .rows-table{
        font-size: 14px;
    }
</style>
    <div class="container">

        <!-- Titulo y de seccion -->
        <div class="row mb-1">
            <div class="col">
                <h3 class="title_body">Control de Escuelas - <span><b>MINEDUC</b></span></h3>
            </div>
        </div>

        <!-- Escuelas Box -->
        <div class="row mb-4">
            <div class="col">

                <!-- Card -->
                <div class="card mb-4">
                    <div class="card-header">
                        <div class="container col d-flex justify-content-between">
                            <h5 class="title_body"><b>Listado de Escuelas</b></h5>
                            <a onclick="return abrir_modal('{% url 'create_escuela' %}')" class="btn btn-success text-white icon_link" id="registrar_escuela">
                                <span class="icon fa fa-plus-square mr-2"></span>
                                <b>Registrar Escuela</b>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="escuelas_table" class="stripe" style="width:100%">
                                <thead>
                                    <tr class="text-uppercase">
                                        <th>Codigo</th>
                                        <th>Nombre</th>
                                        <th>Direccion</th>
                                        <th>Departamento</th>
                                        <th>Municipio</th>
                                        <th>Fondo</th>
                                        <th>Usuario</th>
                                        <th style="text-align: center;">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for escuela in escuela  %}
                                        <tr class="rows-table text-uppercase" id="{{escuela.codigo}}">
                                            <td>{{escuela.codigo}}</td>
                                            <td>{{escuela.nombre}}</td>
                                            <td>{{escuela.direccion}}</td>
                                            <td>{{escuela.departamento}}</td>
                                            <td>{{escuela.municipio}}</td>

                                            <td style="text-align: center;">
                                                {% if escuela.existe_fondo_sql == True %}
                                                    <span class="fas fa-check-circle text-success" style="font-size:30px"></span>
                                                {% else %}
                                                    <span class="fas fa-times text-danger" style="font-size:30px"></span>
                                                {% endif %}
                                            </td>

                                            <td style="text-align: center;">
                                                {% if escuela.existe_usuario_sql == True %}
                                                    <span class="fas fa-user-check text-success" style="font-size:30px"></span>
                                                {% else %}
                                                    <a class="add_user" onclick="return abrir_modal('{% url 'create_escuela_usuario' %}')" href="" data-escuela="{{escuela.codigo}}">
                                                        <span class="fas fa-user-times text-danger" style="font-size:30px"></span>
                                                    </a>
                                                {% endif %}
                                            </td>

                                            <td style="text-align: center;">
                                                <button class="btn btn-warning circle-btn mr-2"
                                                    onclick="return abrir_modal('{% url 'actualizar_escuela' escuela.pk %}')">
                                                        <span class="fas fa-pencil-alt"></span>
                                                </button>
                                                <button class="btn btn-danger circle-btn" onclick="return abrir_modal('{% url 'eliminar_escuela' escuela.pk %}')" id="btn_escuela_delete">
                                                        <span class="fas fa-trash-alt"></span>
                                                </button>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <hr>

    </div>
{% endblock content %}

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

{% block js_block %}
<script>
    $(document).ready( function () {
        $('#escuelas_table').DataTable( {
            "language": {
                "lengthMenu": "Mostrar _MENU_ registros por página",
                "zeroRecords": "No se encontraron Registros - Lo sentimos..!",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros Disponibles",
                "search": "Buscar:",
                "infoFiltered": "(filtered from _MAX_ total records)",
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "thousands": ",",
                "decimal": "",
                "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            },
            "scrollX": true
        });
    });
</script>
{% endblock js_block %}