core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import DepartamentoListView, Home, HomeSinPrivilegios

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name="core/login.html"), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name="core/login.html"), name='logout'),
    path('', Home.as_view(), name='home'),
    path('NoPermitido/', HomeSinPrivilegios.as_view(), name='sin_privilegios'),
]

planificacion/urls.py
from django.urls import path
from .views import PlanificacionView, PlanificacionCreateView, ActividadCreateView, ActividadDelete, PagoActividadCreateView

urlpatterns = [
	path('planificacion/', PlanificacionView.as_view(), name='planificacion'),
	path('planificacion/create', PlanificacionCreateView.as_view(), name='add_planificacion'),
	path('actividad/create', ActividadCreateView.as_view(), name='add_actividad'),
	path('actividad/pago', PagoActividadCreateView.as_view(), name='add_pago'),
	path('actividad/delete/<int:pk>', ActividadDelete.as_view(), name='delete_actividad'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('escuelas/', include('escuela.urls')),
    path('comite/', include('comite.urls')),
    path('perfil/', include('perfil.urls')),
    path('', include('planificacion.urls')),
]

planificacion/models.py
from django.db import models

# Importamos pra la conecxion a la BD
from django.db import connection

from django.core.exceptions import ValidationError

from comite.models import Comite, Fondo

# Create your models here.

class Planificacion(models.Model):
    comite = models.ForeignKey(Comite, on_delete=models.CASCADE, verbose_name='Comite')
    descripcion = models.TextField('Descripcion')
    fecha_crea = models.DateField("Fecha Creacion", auto_now_add=True)
    ciclo = models.PositiveSmallIntegerField('Ciclo')

    class Meta:
        ordering = ['-ciclo']
        unique_together = ['comite', 'ciclo']
        verbose_name = "Planificacion"
        verbose_name_plural = "Planificaciones"
        db_table = 'Planificacion'

    def actividades_registradas(self):
        valor = 0
        for a in Actividad.objects.all():
            if a.plainficacion == self.id:
                valor = valor+1
        return valor

    def actividades_finalizadas(self):
        valor = 0
        for a in Actividad.objects.all():
            if a.plainficacion == self.id:
                if a.estado == 0:
                    valor = valor+1
        return valor

    def actividades_aprobadas(self):
        valor = 0
        for a in Actividad.objects.all():
            if a.plainficacion == self.id:
                if a.estado == 1:
                    valor = valor+1
        return valor

    def llamar_saldo(self):
        saldo = Fondo.objects.filter(comite=self.comite, ciclo=self.ciclo).get()
        return saldo.saldo

    def __str__(self):
        return 'Ciclo: %s, %s' % (self.ciclo, self.comite)

ACTIVIDAD_CHOICES = [
    ('Deportiva', 'Deportiva'),
    ('Cultural', 'Cultural'),
    ('Social', 'Social'),
    ('Artistica', 'Artistica'),
    ('Academica', 'Academica'),
]

class Actividad(models.Model):
    tipo = models.CharField('Tipo de Actividad', choices=ACTIVIDAD_CHOICES, max_length=25)
    descripcion = models.TextField('Descripcion')
    fecha_prog = models.DateField('Fecha Programada')
    costo = models.DecimalField('Costo', max_digits=10, decimal_places=2)
    estado = models.PositiveSmallIntegerField('Estado', default=2)
    fecha_crea = models.DateField("Fecha Creacion", auto_now_add=True)
    plainficacion = models.ForeignKey(Planificacion, on_delete=models.CASCADE, verbose_name='Comite')

    class Meta:
        verbose_name = "Actividad"
        verbose_name_plural = "Actividads"
        db_table = 'Actividad'

    def costo_real(self):
        saldo = 0
        for pago in PagoActividad.objects.filter(actividad=self.id):
            saldo = pago.valor+saldo
        saldo = float(saldo)
        return saldo

    def estado_actividad(self):
        if self.estado == 0:
            return 'Finalizada'
        elif self.estado == 1:
            return 'Autorizada'
        elif self.estado == 2:
            return 'Ingresada'

    def __str__(self):
        return '%s %s' % (self.plainficacion.ciclo, self.descripcion)

def comite_directory_path(instance, filename):
    return 'Actividad/' + filename

class PagoActividad(models.Model):
    actividad = models.ForeignKey(Actividad, on_delete=models.CASCADE, verbose_name='Actividad')
    factura = models.FileField(upload_to='uploads/', blank=True)
    valor = models.DecimalField('Costo', max_digits=10, decimal_places=2)
    descripcion = models.TextField('Descripcion')
    fecha_crea = models.DateField("Fecha Creacion", auto_now_add=True)

    class Meta:
        db_table = 'PagoActividad'
        verbose_name = "PagoActividad"
        verbose_name_plural = "PagoActividades"

    def validar_retiro_sql(self):
        ciclo = self.actividad.plainficacion.ciclo
        comite = self.actividad.plainficacion.comite
        fondo = Fondo.objects.filter(comite=comite, ciclo=ciclo).get()
        saldo = fondo.saldo
        dato = 0
        result = False
        #with connection.cursor() as cursor:
        #    dato = cursor.callfunc("VALIDAR_PAGO_ACTIVIDAD", int, [saldo, self.valor, fondo.pk])
        # Segun el procedimiento creado si retorna 0 es que existe uno o mas comites
        if  saldo < self.valor:
            result = True
        else:
            result = False
        return result

    def __str__(self):
        return 'Costo: %s, fecha_crea: %s' % (
            self.valor, self.fecha_crea
            )

    def clean(self, **kwargs):
        super(PagoActividad, self).clean()
        # Si nos retorna verdadero lanzamos un error
        respuestaSQL_Retiro = self.validar_retiro_sql()
        if respuestaSQL_Retiro is True:
            raise ValidationError('No se Cuenta con Suficiente Saldo')

planificacion/forms.py
from django import forms
from django.forms import ClearableFileInput
from .models import Planificacion, Actividad, PagoActividad

# from betterforms.multiform import MultiModelForm
class CustomClearableFileInput(ClearableFileInput):
    template_with_clear = '<br>  <label for="%(clear_checkbox_id)s">%(clear_checkbox_label)s</label> %(clear)s'


class PagoActividadForm(forms.ModelForm):
    class Meta:
        model = PagoActividad
        fields = '__all__'
        widgets = {
            'factura': CustomClearableFileInput
        }

planificacion/views.py
'''
    from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.http import HttpResponseRedirect, HttpResponseNotFound

from django.core import serializers
from django.http import JsonResponse
import json

from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin
from perfil.models import UsuarioEscuela
from escuela.models import Escuela, Comite
from planificacion.models import Planificacion
from padre.models import PadreFamilia
from perfil.models import UsuarioComite

from .forms import IntegranteForm
from .models import Integrante, Fondo, MovimientoFondo

from easy_pdf.views import PDFTemplateView

from core.views import SinPrivilegios
'''

from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.http import Http404

from django.core import serializers
from django.http import JsonResponse
import json

from core.views import SinPrivilegios

from django.core.exceptions import SuspiciousOperation
from django.contrib import messages

from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView

from .models import Planificacion, Actividad, PagoActividad
from escuela.models import Comite
from perfil.models import UsuarioComite

from .forms import PagoActividadForm

from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView

# Formularios en linea
from django.forms import inlineformset_factory

# Create your views here.

class PlanificacionView(SinPrivilegios, TemplateView):
    permission_required = ['escuela.view_comite']
    login_url = 'login'
    template_name = "planificacion/planificacion_list.html"
    context = []

    def get_context_data(self, **kwargs):
        context = super(PlanificacionView, self).get_context_data(**kwargs)
        context.update(**kwargs)
        # Iniciamos a enviar los contextos

        # Obtenemos el usuario
        usuario = self.request.user

        # Obtenemos el Perfil
        perfil = UsuarioComite.objects.filter(usuario=usuario).get()
        # Obtenemos el Comite
        comite = None
        for c in Comite.objects.all():
        	if perfil.comite == c:
        		comite = c
        context['comite'] = comite
        # Obtenemos las Planificaciones
        planificaciones = Planificacion.objects.filter(comite=comite)
        context['planificaciones'] = planificaciones
        # Traemos todas las actividades
        context['actividades'] = Actividad.objects.all()
        return context

class PlanificacionCreateView(SinPrivilegios, CreateView):
    permission_required = ['planificacion.add_planificacion',]
    model = Planificacion
    fields = '__all__'
    success_url = reverse_lazy('planificacion')

    def form_invalid(self, form):
        messages.error(request, "Error")

class ActividadCreateView(SinPrivilegios, CreateView):
    permission_required = ['planificacion.add_actividad',]
    model = Actividad
    fields = '__all__'
    success_url = reverse_lazy('planificacion')

    def form_invalid(self, form):
        messages.error(request, "Error")

class ActividadDelete(SinPrivilegios, DeleteView):
    permission_required = ['planificacion.delete_actividad']
    model = Actividad
    success_url = reverse_lazy('planificacion')

class PagoActividadCreateView(SinPrivilegios, CreateView):
    permission_required = ['planificacion.add_pagoactividad',]
    model = PagoActividad
    form_class = PagoActividadForm
    success_url = reverse_lazy('planificacion')

    def form_invalid(self, form):
        messages.error(request, "Error")

planificacion/templates/planificacion/actividad_confirm_delete.html
<div class="modal-dialog shadow">
	<div class="modal-content">

		<form method="post">{% csrf_token %}
			<!-- Card Body -->
			<div class="card-body">
							<div class="row no-gutters aling-items-center">
								<div class="col mr-2">
									<div class="container">
										<div class="row">
											<p><span class="fas fa-exclamation-circle text-warning mr-2" style="font-size:26px"></span>¿Está seguro de que quiere borrar: <b>"Esta Actividad"</b>?</p>
											<small><span class="text-danger">
												<span class="fas fa-exclamation text-danger mr-2"></span>Al hacer click en <b>Sí,</b> se eliminara el objeto y no se podra recuperar..!
											</span></small>
										</div>
									</div>
								</div>
							</div>
			</div>

			<!-- Card Footer -->
			<div class="card-footer">
				<div class="row">
					<div class="col d-flex justify-content-between">
						<button id="delete" class="btn btn-warning text-white" value="">Sí, Estoy Seguro</button>
						<button onclick="return cerrar_modal()" type="submit" class="btn btn-danger">Cancelar</button>
					</div>
				</div>
			</div>
		</form>

	</div>

</div>

		<small class="text-danger">
			{% if form.errors %}
				{% for field in form %}
					{% if field.errors %}
						{% for error in field.errors  %}
							<p>{{field.name}} {{error|escape}}</p>
						{% endfor %}
					{% endif %}
				{% endfor %}

				{% if form.non_field_errors %}
					{% for error in field.errors  %}
							{{error|escape}}
						{% endfor %}
				{% endif %}
			{% endif%}
		</small>

	</div>
</div>

<script>

	// Eliminar con ajax una escuela
	var token = $('input[name=csrfmiddlewaretoken]').val();
	$.ajaxSetup({
		beforeSend: function(xhr, settings) {
			if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))){
				xhr.setRequestHeader("X-CSRFToken", token);
			}
		}
	});

		$("#delete").click(function(e){
			e.preventDefault();
			var id = "{{ object.pk }}";
			var template = "{% url 'delete_actividad' object.pk %}";
			var data = {"id":id};
			data = JSON.stringify(data);

			$.ajax({
                type: "POST",
                url: template,
                data: data,
                beforeSend: function(xhr, settings){
                	$.ajaxSettings.beforeSend(xhr, settings);
                },
                success: function(response){
                    cerrar_modal();
                    location.reload();
                },
                error: function(jqXHR, textStatus, errorThrow){
                    console.log(textStatus, errorThrow);
                    cerrar_modal();
                }
            });

		});

		/*
        $("#delete").click(function(e){
            e.preventDefault();
            //alert("Probando");
            var id = {{escuela.pk}};
            var data = {"id":id};
            data = JSON.stringify(data);
        })

            
            $.ajax({
                type: "POST",
                url: template,
                data: data,
                success: function(response){
                    console.log(response);
                    cerrar_modal();
                    alert(response);
                },
                error: function(jqXHR, textStatus, errorThrow){
                    console.log(textStatus, errorThrow);
                    cerrar_modal();
                }
            });*/
</script>

planificacion/templates/planificacion/actividad_form.html
{% load widget_tweaks %}
{% load static %}

<style>
	.activity{
		border-left: 5px solid #00CE13;
		border-bottom: 5px solid #00CE13;
		box-shadow: 5px 5px 5px;
	}
</style>
<div class="modal-dialog modal-lg shadow">
	<div class="modal-content">

		<div class="card activity">
			<div class="card-header">
				<h3 id="titladdeactividad" class="text-succes text-uppercase">
					<span class="fas fa-puzzle-piece mr-2"></span>
					Registrar nueva actividad al plan ciclo:
				</h3>
			</div>
			<form id="createActividad" method="POST" action="{% url 'add_actividad' %}">{% csrf_token %}
				<!-- Card Body -->
				<div class="card-body ">
					<div class="row no-gutters aling-items-center">
						<div class="col">
							<div class="container">
								<div class="row text-uppercase text-primary">
									<div id="form" class="col-12">

										<div class="row">
											<div class="col-4">
												<div class="form-group">
												    {% render_field form.tipo class+="form-control" placeholder="Ingrese el DPI" autocomplete='off' %}
												 </div>
											</div>
											<div class="col-4">
												<div class="form-group">
													<input id="id_fecha_prog" name="fecha_prog" class="form-control" type="date">
												 </div>
											</div>
											<div class="col-4">
												<div class="form-group">
												    {% render_field form.costo class+="form-control" placeholder="Costo aproximado" autocomplete='off' %}
												 </div>
											</div>
										</div>

										<div class="row">
											<div class="col">
												<div class="form-group">
												    {% render_field form.descripcion rows="4" class+="form-control" autocomplete='off' placeholder="Agrege una descripcion de la actividad" %}
												    {% render_field form.estado rows="4" class+="form-control" autocomplete='off' placeholder="Agrege una descripcion de la actividad" %}
												    {% render_field form.plainficacion rows="4" class+="form-control" autocomplete='off' placeholder="Agrege una descripcion de la actividad" %}
												 </div>
											</div>
										</div>
									</div>
							</div>
						</div>
					</div>
				</div>
				</div>

				<!-- Card Footer -->
				<div class="card-footer">
					<div class="row">
						<div class="col d-flex justify-content-around">
							<button id="delete" type="submit" class="btn btn-success text-white" value="">Guardar</button>
							<button onclick="return cerrar_modal()" class="btn btn-danger">Cancelar</button>
						</div>
					</div>
				</div>
			</form>
		</div>

	</div>

</div>

<script>
	$('#id_plainficacion').val(id_plan);
	$('#id_plainficacion').hide();
	$('#id_estado').hide();
	var title = $('#titladdeactividad').text() + anio
	$('#titladdeactividad').text(title);

	$('#createActividad').submit(function(event) {
		/* Act on the event */
		event.preventDefault();

		// Serializamos la data para enviar el form data
		var serializeData = $(this).serialize();

		// Hacemos el llamado Post con ajax
		$.ajax({
			type: 'POST',
			url: "{% url 'add_actividad' %}",
			data: serializeData,
			success: function(response){
				cerrar_modal();
				var msg = 'Se creo una nueva Actividad' + anio
				$.confirm({
				    title: 'Exito!',
				    content: msg,
				    buttons: {
				        Ok: {
				            text: 'Ok',
				            btnClass: 'btn-green',
				            keys: ['enter',],
				            action: function(){
				                window.location.reload();
				            }
				        }
				    }
				});
			},
			error: function(response){
				var title = `<h3 class='Text-danger'><span class="fas fa-exclamation-circle"></span> Error</h3>`
				mensaje(title, 'Verifique los datos', 'red')
			}
		})
	});
</script>

planificacion/templates/planificacion/pagoactividad_form.html
{% load widget_tweaks %}
{% load static %}

<div class="modal-dialog shadow">
	<div class="modal-content">

		<form id="FormPago" method="POST" action="{% url 'add_pago' %}">{% csrf_token %}
			<!-- Card Body -->
			<div class="card-header text-uppercase">
				<h4>Registrar Pago:</h4>
			</div>
			<div class="card-body">
				<div class="row no-gutters aling-items-center">
					<div class="col mr-2">
						<div class="container">

							<div id="form" class="col-12">

								<div class="row">
									<div class="col">
										<div class="form-group">
											{% render_field form.actividad class+="form-control" %}
											{% render_field form.fecha_crea class+="form-control" %}
											<span id="id_act"></span>
										</div>
									</div>
								</div>

								<div class="row">
									<div class="col-6">
										<div class="form-group">
											{% render_field form.valor class+="form-control" placeholder="Monto a Pagar" autocomplete='off' %}
										</div>
									</div>
								</div>

								<div class="row">
									<div class="col">
										<div class="custom-file mb-3">
										    {% render_field form.factura class+="form-control" %}
										</div>
									</div>
								</div>

								<div class="row">
									<div class="col">
										<div class="form-group">
											{% render_field form.descripcion rows="4" class+="form-control" autocomplete='off' placeholder="Agrege una descripcion del pago" %}
										</div>
									</div>
								</div>

							</div>

						</div>
					</div>
				</div>
			</div>

			<!-- Card Footer -->
			<div class="card-footer">
				<div class="row">
					<div class="col d-flex justify-content-between">
						<button id="delete" type="submit" class="btn btn-success text-white" value="">Sí, Estoy Seguro</button>
						<button onclick="return cerrar_modal()" class="btn btn-danger">Cancelar</button>
					</div>
				</div>
			</div>
		</form>
		<small style="color:red">
			{% if form.errors %}
		        {% for field in forms %}
		          {% if field.errors %}
		            {% for error in field.errors %}
		              	{{error|escape}}
		            {% endfor %}
		          {% endif %}
		        {% endfor %}

		        {% if form.non_field_errors %}
		          {% for error in form.non_field_errors %}
						{{error|escape}}
		          {% endfor %}
		        {% endif %}
		      {% endif %}
		</small>

	</div>

</div>

<script>
	
	console.log('Actividad: '+ activity);
	$('#id_actividad').val(activity);
	$('#id_actividad').hide();
	$('#FormPago').submit(function(event) {
			/* Act on the event */


			event.preventDefault();
			//alert('Realiaras un pago')

			// Serializamos la data para enviar el form data
			var serializeData = $(this).serialize();

			// Hacemos el llamado Post con ajax
			$.ajax({
				type: 'POST',
				url: "{% url 'add_pago' %}",
				data: serializeData,
				success: function(response){
					cerrar_modal();
					window.location.reload();
				},
				error: function(response){
					var title = `<h3 class='Text-danger'><span class="fas fa-exclamation-circle"></span> Error</h3>`;
					mensaje(title, 'No se cuenta con suficientes fondos', 'red');
					cerrar_modal();
				}
			})
		});
</script>

planificacion/templates/planificacion/pagoactividad_form21.html
{% load widget_tweaks %}
<form method="POST">{% csrf_token %}
	{{form}}
	<button type="submit">Enviar</button>
</form>
<small style="color:red">
			{% if form.errors %}
		        {% for field in forms %}
		          {% if field.errors %}
		            {% for error in field.errors %}
		              	{{error|escape}}
		            {% endfor %}
		          {% endif %}
		        {% endfor %}

		        {% if form.non_field_errors %}
		          {% for error in form.non_field_errors %}
						{{error|escape}}
		          {% endfor %}
		        {% endif %}
		      {% endif %}
		</small>

planificacion/templates/planificacion/planificacion_form.html
<div class="modal-dialog shadow">
	<div class="modal-content">

		<form id="createPlanform" method="POST" action="{% url 'add_planificacion' %}">{% csrf_token %}
			<!-- Card Body -->
			<div class="card-body">
				<div class="row no-gutters aling-items-center">
					<div class="col mr-2">
						<div class="container">
							<div class="row text-uppercase text-primary">
								<p><span class="fas fa-exclamation-circle text-uppercase mr-2" style="font-size:26px"></span>Se creara una Planificacion Correspondiente al Ciclo: <b class="ciclo"></b></p>
								<div id="form">
									{{form}}
								</div>
						</div>
					</div>
				</div>
			</div>
			</div>

			<!-- Card Footer -->
			<div class="card-footer">
				<div class="row">
					<div class="col d-flex justify-content-between">
						<button id="delete" type="submit" class="btn btn-success text-white" value="">Sí, Estoy Seguro</button>
						<button onclick="return cerrar_modal()" class="btn btn-danger">Cancelar</button>
					</div>
				</div>
			</div>
		</form>

	</div>

</div>

<script>
	var anio = (new Date).getFullYear();
	$('.ciclo').text(anio);
	$('#id_ciclo').val(anio);
	$('#id_comite').val(id_comite);
	$('#id_descripcion').val(`Planificacion correspondiente al ciclo ` + anio +
		` para uso de actividades escolares, artisticas y culturales de `+ escuela);
	$('#form').hide();
	$('#createPlanform').submit(function(event) {
		/* Act on the event */
		event.preventDefault();

		// Serializamos la data para enviar el form data
		var serializeData = $(this).serialize();

		// Hacemos el llamado Post con ajax
		$.ajax({
			type: 'POST',
			url: "{% url 'add_planificacion' %}",
			data: serializeData,
			success: function(response){
				cerrar_modal();
				mensaje('Exito', 'Se creo una nueva Planificación', 'green')
				window.location.reload();
			},
			error: function(response){
				var title = `<h3 class='Text-danger'><span class="fas fa-exclamation-circle"></span> Error</h3>`
				mensaje(title, 'Verifique los datos', 'red')
			}
		})
	});
</script>