comite/urls.py
from django.urls import path
from .views import ComiteEscuela, IntegranteCreate, SearchPadre, IntegranteDelete, \
MovimientoCreateView, RegistroPDFView, ComiteUsuario

urlpatterns = [
	path('usuario/', ComiteUsuario.as_view(), name='comite_usuario'),
	path('escuela/', ComiteEscuela.as_view(), name='comite'),
	path('registrar/integrante/', IntegranteCreate.as_view(), name='crear_intengrante'),
	path('search/padre/', SearchPadre, name='padre_ajax'),
	path('eliminar/integrante/<int:pk>', IntegranteDelete.as_view(), name='eliminar_intengrante'),
	path('asignarFondo/', MovimientoCreateView.as_view(), name='asignar'),
	path('registro/movimientos/', RegistroPDFView.as_view(), name='pdf_movimientos'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import DepartamentoListView, Home, HomeSinPrivilegios

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name="core/login.html"), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name="core/login.html"), name='logout'),
    path('', Home.as_view(), name='home'),
    path('NoPermitido/', HomeSinPrivilegios.as_view(), name='sin_privilegios'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('escuelas/', include('escuela.urls')),
    path('comite/', include('comite.urls')),
    path('perfil/', include('perfil.urls')),
    path('', include('planificacion.urls')),
]

comite/models.py
from django.db import models

# Importamos pra la conecxion a la BD
from django.db import connection

from django.core.exceptions import ValidationError

from escuela.models import Escuela, Comite
from padre.models import PadreFamilia
import datetime

# Create your models here.

PUESTOS_CHOICES = [
    ('1', 'Presidente'),
    ('2', 'Vice Presidente'),
    ('3', 'Secretario'),
    ('4', 'Tesorero'),
    ('5', 'Vocal'),
]

class Integrante(models.Model):
    comite = models.ForeignKey(Comite, on_delete=models.CASCADE, verbose_name='Comite')
    puesto = models.CharField('Puesto', choices=PUESTOS_CHOICES, max_length=1)
    padre = models.OneToOneField(PadreFamilia, on_delete=models.CASCADE, verbose_name='Padre de Familia', blank=True)

    def retornarPuesto(self):
        if self.puesto == '1':
            return 'Presidente'
        elif self.puesto == '2':
            return 'Vice-Presidente'
        elif self.puesto == '3':
            return 'Secretario'
        elif self.puesto == '4':
            return 'Tesorero'
        else:
            return 'Vocal'


    class Meta:
        ordering = ['puesto']
        unique_together = ['puesto', 'comite']
        verbose_name = "Integrante"
        verbose_name_plural = "Integrantes"

    def __str__(self):
        return '%s %s: %s' % (self.pk, self.retornarPuesto(), self.padre)


class Fondo(models.Model):
    comite = models.ForeignKey(Comite, on_delete=models.CASCADE, verbose_name='Comite')
    fecha = models.DateField('Fecha de Creacion', auto_now_add=True)
    montoInicial = models.DecimalField('Monto Inicial', max_digits=10, decimal_places=2, default=0.00)
    estado = models.BooleanField('Estado')
    saldo = models.DecimalField('Saldo', max_digits=10, decimal_places=2)
    ciclo = models.PositiveSmallIntegerField('Ciclo')


    class Meta:
        unique_together = ['ciclo', 'comite']
        verbose_name = "Fondo"
        verbose_name_plural = "Fondos"
        db_table = 'Fondo'
        ordering = ['-ciclo']

    def estado(self):
        if self.estado is True:
            return 'Activo'
        else:
            return 'Inactivo'

    def __str__(self):
        return '%s %s' % (self.comite, self.ciclo)

class MovimientoFondo(models.Model):
    fondo = models.ForeignKey(Fondo, on_delete=models.CASCADE, verbose_name='Fondo')
    fecha = models.DateField('Fecha', auto_now_add=True)
    valor = models.DecimalField('Valor', max_digits=10, decimal_places=2)
    tipoMovimiento = models.BooleanField('Tipo de Movimiento')
    observaciones = models.TextField('Observaciones')
    ciclo = models.PositiveSmallIntegerField('Ciclo')


    class Meta:
        ordering = ['-tipoMovimiento']
        verbose_name = "MovimientoFondo"
        verbose_name_plural = "MovimientosFondo"
        db_table = 'MovimientosFondo'


    def tipo_movimiento(self):
        if self.tipoMovimiento is True:
            return 'Deposito'
        else:
            return 'Retiro'

    def __str__(self):
        return 'Comite: %s, Tipo: %s, Fecha: %s, Valor: %s' % (
            self.fondo.comite, self.tipo_movimiento(),
            self.fecha, self.valor
            )

    ''' Llamamos a una funcion en la base de datos,
        y evaluamos si existe un movimiento de deposito de este año '''
    def validar_deposito_sql(self):
        result = False
        year = datetime.date.today().year
        int(year)
        # Obtenemos todos los movimientos para este fondo
        # Segun el procedimiento creado si retorna 0 es que existe uno o mas comites
        if  MovimientoFondo.objects.filter(fondo=self.fondo, tipo=True, ciclo=year).exists():
            result = True
        else:
            result = False
        return result


    def clean(self, **kwargs):
        super(MovimientoFondo, self).clean()
        # Si nos retorna verdadero lanzamos un error
        respuestaSQL_Deposito = self.validar_deposito_sql()
        if respuestaSQL_Deposito is True:
            raise ValidationError('Ya existe una asignacion')

comite/forms.py
from django import forms
from .models import Integrante

from betterforms.multiform import MultiModelForm

from padre.models import PadreFamilia


class IntegranteComiteForm(forms.ModelForm):
    class Meta:
        model = Integrante
        fields = '__all__'

class PersonaForm(forms.ModelForm):
    class Meta:
        model = PadreFamilia
        fields = '__all__'

class IntegranteForm(MultiModelForm):
    form_classes = {
        'integrante': IntegranteComiteForm,
        'persona': PersonaForm,
    }

comite/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.http import HttpResponseRedirect, HttpResponseNotFound

from django.core import serializers
from django.http import JsonResponse
import json

from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin
from perfil.models import UsuarioEscuela
from escuela.models import Escuela, Comite
from planificacion.models import Planificacion
from padre.models import PadreFamilia
from perfil.models import UsuarioComite

from .forms import IntegranteForm
from .models import Integrante, Fondo, MovimientoFondo

from easy_pdf.views import PDFTemplateView

from core.views import SinPrivilegios

# Create your views here.

'''     -       VISTAS PRINCIPALES DEL COMITE       -    '''
class ComiteEscuela(SinPrivilegios, TemplateView):
    permission_required = ['escuela.view_comite']
    login_url = 'login'
    template_name = "comite/comite.html"
    context = []

    def get_context_data(self, **kwargs):
        context = super(ComiteEscuela, self).get_context_data(**kwargs)
        context.update(**kwargs)
        # usuario =  UsuarioEscuela.objects.filter(usuario=)
        usuario = self.request.user

        context['perfil'] = UsuarioEscuela.objects.filter(usuario=usuario).get()
        context['comite'] = Comite.objects.all()
        user = UsuarioEscuela.objects.filter(usuario=usuario).get()
        comiteEscuela = Comite.objects.filter(escuela=user.escuela).get()
        user_comite = UsuarioComite.objects.filter(comite=comiteEscuela)
        context['usuario'] = user_comite
        fondo_comite = Fondo.objects.filter(comite=comiteEscuela).first()
        comite_fondo = fondo_comite

        movimientos_fondo = MovimientoFondo.objects.filter(fondo=comite_fondo)
        # context['fondo'] = Fondo.objects.filter(comite=comiteEscuela).first()
        context['fondo'] = Fondo.objects.filter(comite=comiteEscuela).first()
        context['movimientos'] = movimientos_fondo
        # context['movimientos'] = MovimientoFondo.objects.filter(fondo=fondo_comite)
        context['integrantes'] = Integrante.objects.filter(comite=comiteEscuela)
        context['planificacion'] = Planificacion.objects.filter(comite=comiteEscuela)
        return context

# Crear un itengrante desde el usuario del COMITE
class IntegranteCreate(SinPrivilegios, CreateView):
    permission_required = ['comite.add_integrante', 'padre.add_padrefamilia']
    model = Integrante
    form_class = IntegranteForm
    success_url = reverse_lazy('comite')

    def form_valid(self, form):
        persona = form['persona'].save()
        integrante = form['integrante'].save(commit=False)
        integrante.padre = persona
        integrante.save()
        return HttpResponseRedirect(reverse_lazy('comite'))

    def form_invalid(self, form):
        return HttpResponseNotFound('<h1>Page not found</h1>')

def SearchPadre(request):
    # Obtenemos el dato que envia el formulario
    dpi = request.GET.get('dpi')

    if PadreFamilia.objects.filter(dpi=dpi):
        padre = PadreFamilia.objects.filter(dpi=dpi).values()
        return JsonResponse({"Padre": list(padre)})
    else:
        return JsonResponse({"error": True, "error": "there was an error"})

# Eliminar un itengrante desde el usuario del COMITE
class IntegranteDelete(SinPrivilegios, DeleteView):
    permission_required = ['comite.delete_integrante', 'padre.delete_padrefamilia']
    model = Integrante
    success_url = reverse_lazy('comite')

class AddFondoCreateView(SinPrivilegios, CreateView):
    permission_required = ['comite.delete_integrante', 'padre.delete_padrefamilia']
    model = Fondo

class MovimientoCreateView(SinPrivilegios, CreateView):
    permission_required = ['comite.add_movimientofondo',]
    model = MovimientoFondo
    fields = '__all__'
    success_url = reverse_lazy('comite')

    def form_invalid(self, form):
        messages.error(request, "Error")


# Vista del comite para el usuario del COMITE
class ComiteUsuario(SinPrivilegios, TemplateView):
    permission_required = ['escuela.view_comite']
    login_url = 'login'
    template_name = "comite/comite_usuario.html"
    context = []

    def get_context_data(self, **kwargs):
        context = super(ComiteUsuario, self).get_context_data(**kwargs)
        context.update(**kwargs)
        # usuario =  UsuarioComite.objects.filter(usuario=)
        usuario = self.request.user

        # Obtenemos el perfil para obtener el comite
        perfil = UsuarioComite.objects.filter(usuario=usuario).get()
        context['perfil'] = perfil
        escuela = Escuela.objects.all()
        ''' Con esta consulta buscamos arriba de comite y
        verificamos que el usuario pertenezca al comite de la escuela '''
        comite_escuela = Comite.objects.select_related('escuela').filter(escuela=perfil.comite.escuela).get()
        context['comite'] = comite_escuela
        # Obtenemos el Fondo
        fondo = Fondo.objects.filter(comite=comite_escuela).first()
        context['fondo'] = Fondo.objects.filter(comite=comite_escuela).first()
        # Envimos los integrantes
        context['integrantes'] = Integrante.objects.filter(comite=comite_escuela)
        # Enviamos los movimientos
        context['movimientos'] = MovimientoFondo.objects.filter(fondo=fondo).exists()
        return context

'''     -       VISTAS DE REPORTE PARA EL COMITE       -    '''

class  RegistroPDFView(PDFTemplateView ):
    template_name  =  'comite/Reportes/registro_movimientos.html'

    def get_context_data(self, **kwargs):
        # usuario =  UsuarioComite.objects.filter(usuario=)
        usuario = self.request.user
        perfil = UsuarioComite.objects.filter(usuario=usuario).get()
        escuela = Escuela.objects.all()
        comite_escuela = Comite.objects.select_related('escuela').filter(escuela=perfil.comite.escuela).get()
        fondo = Fondo.objects.filter(comite=comite_escuela).first()
        movimientos = MovimientoFondo.objects.filter(fondo=fondo)

        return super(RegistroPDFView, self).get_context_data(
            pagesize='Legal landscape',
            title='RegistroMovimientosPDF',
            usuario=usuario,
            movimientos=movimientos,
            fondo=fondo,
            comite_escuela=comite_escuela,
            **kwargs
            )

comite/templates/comite/comite.html
{% extends "core/base.html" %}

{% block content %}
<style>
	.part-table{
		border-right: 1px solid gray;
	}
	.fila-fondo{
		border-bottom: 1px solid gray;	
	}
	a.add_comite_user{
		text-decoration: none;
	}
	a.add_comite_user:hover{
		font-weight: bold;
	}
	a.text-success:hover{
		text-decoration: none;
	}
	.btn-xl{
		border-radius: 25px;
	}
</style>
{% for c in comite  %}
	{% if c.escuela == perfil.escuela %}
	<div class="container">

		<!-- Alerta Usuario -->
		{% if usuario %}
		{% else %}
			<div id="alertUserComite">
				<div class="alert alert-danger d-flex text-uppercase" role="alert">
					No se ha creado un usuario para este comite..!
					<a id="addComiteUser" onclick="return abrir_modal('{% url 'create_comite_usuario' %}')" class="ml-auto text-danger add_comite_user">
						<span class="fas fa-user-plus mr-2"></span>
						Crear Usuario
					</a>
				</div>
			</div>
		{% endif %}

		<div class="card border-primary mb-3">
			<div class="card-header text-primary">
				<span class="fas fa-users mr-2"></span>
				{{c.nombre}}
			</div>
			<div class="card-body">
			    <div class="container">
			    	<div class="row">

			    		<!-- Division parte Derecha Integrantes -->
			    		<div class="col-8 part-table">
			    			<div class="container">
			    				<div class="row">
			    					<div>
			    						<h5 class="text-uppercase">
			    							<span class="text-info fas fa-users mr-2"></span>
			    							<b>Integrantes  del Comite</b>
			    						</h5>
			    					</div>
			    					<div class="ml-auto">
			    						<b>
			    						<a class="text-success" id="addIntegrante" onclick="return abrir_modal('{% url 'crear_intengrante' %}')" href="" data-comite="{{c.id}}">
			    							<span class="icon fa fa-plus-square mr-2"></span>
			    							Agregar integrante
			    						</a>
			    						</b>
			    					</div>
			    				</div>
			    				<table id="integrantes" class="table table-sm table-striped" style="width:100%">
			    					<thead>
			    					    <tr class="text-uppercase">
			    					        <th>Puesto</th>
			    					        <th>Nombre</th>
			    					        <th class="" style="text-align:center;">Editar / Eliminar</th>
			    					    </tr>
			    					</thead>
			    					<tbody>
			    						{% for i in integrantes %}
			    						<tr class="text-uppercase">
			    					        <td>{{i.retornarPuesto}}</td>
			    					        <td>{{i.padre}}</td>
			    					        <td style="text-align:center;">
			    				                <button class="btn btn-danger btn-xl mr-2"
			    				                    onclick="return abrir_modal('{% url 'eliminar_intengrante' i.pk %}')">
			    				                        <span class="fas fa-trash-alt"></span>
			    				                </button>
			    				            </td>
			    					    </tr>
			    					    {% endfor %}
			    					</tbody>
			    				</table>
			    			</div>
			    		</div>

			    		<!-- Division parte Iquierda -->
			    		<div class="col-4">

			    			<!-- Division de Fondo -->
			    			<div class="row fila-fondo mb-4" id="saldoDiv">
			    				<div class="container">
			    					<h5 class="text-uppercase">
			    						<b>
			    							<span id="fondo_span" class="text-uppercase text-warning fas fa-coins mr-2" data-pk="{{fondo.pk}}"></span>
			    							Fondo Ciclo: {{fondo.ciclo}}
			    						</b>
			    					</h5>
			    					<div class="d-flex justify-content-center">
			    						<h5 class="text-uppercase">
			    							<button onclick="return abrir_modal('{% url 'asignar' %}')" class="btn btn-warning text-uppercase" id="asignarFondo">
												<span class="fas fa-money-bill-alt mr-2"></span>
			    								Asignar
			    							</button>
			    							<a download="RegistroMovimientos.pdf" href="{% url 'pdf_movimientos' %}" class={% if movimientos %} "text-uppercase btn btn-secondary" {% else %} "text-uppercase disabled btn"{% endif %}>
												<span class="fas fa-tasks mr-2"></span>
			    								Ver Registro
			    							</a>
			    						</h5>
			    					</div>
			    					<div class="container">
			    						<h4 class="text-right">Saldo: <b>Q. {{fondo.saldo}}</b></h4>
			    					</div>
			    				</div>
			    			</div>

			    			<!-- Division de Planificacion -->
			    			<div class="row">
			    				<div class="container">
			    					<h5 class="text-uppercase">
			    						<b>
			    							<span class="text-info far fa-list-alt mr-2"></span>
			    							Planificacion
			    						</b>
			    					</h5>
			    					<div class="d-flex justify-content-center">
			    						<h5 class="text-uppercase">
			    							<button class=" {% if planificacion %} btn btn-info {% else %} disabled btn btn-dark{% endif %}btn btn-lg text-uppercase">
												<span class="fas fa-file-download mr-2"></span>
			    								Descargar
			    							</button>
			    						</h5>
			    					</div>
			    				</div>
			    			</div>
			    		</div>
			    	</div>
			    </div>
			</div>
		</div>
	</div>
	{% endif %}
{% endfor %}
{% endblock content %}

{% block js_block %}
<script>
    $(document).ready( function () {


    });
</script>
{% endblock js_block %}

comite/templates/comite/comite_usuario.html
{% extends "core/base.html" %}

{% block content %}
<style>
	.part-table{
		border-right: 1px solid gray;
	}
	.fila-fondo{
		border-bottom: 1px solid gray;	
	}
	a.add_comite_user{
		text-decoration: none;
	}
	a.add_comite_user:hover{
		font-weight: bold;
	}
	a.text-success:hover{
		text-decoration: none;
	}
	.btn-xl{
		border-radius: 25px;
	}
</style>

	<div class="container">

		<div class="card border-primary mb-3">
			<div class="card-header text-primary">
				<span class="fas fa-users mr-2"></span>
				{{comite.nombre}}
			</div>
			<div class="card-body">
			    <div class="container">
			    	<div class="row">

			    		<!-- Division parte Derecha Integrantes -->
			    		<div class="col-8 part-table">
			    			<div class="container">
			    				<div class="row">
			    					<div>
			    						<h5 class="text-uppercase">
			    							<span class="text-info fas fa-users mr-2"></span>
			    							<b>Integrantes  del Comite</b>
			    						</h5>
			    					</div>
			    				</div>
			    				<table id="integrantes" class="table table-sm table-striped" style="width:100%">
			    					<thead>
			    					    <tr class="text-uppercase">
			    					        <th>Puesto</th>
			    					        <th>Nombre</th>
			    					    </tr>
			    					</thead>
			    					<tbody>
			    						{% for i in integrantes %}
			    						<tr class="text-uppercase">
			    					        <td>{{i.retornarPuesto}}</td>
			    					        <td>{{i.padre}}</td>
			    					    </tr>
			    					    {% endfor %}
			    					</tbody>
			    				</table>
			    			</div>
			    		</div>

			    		<!-- Division parte Iquierda -->
			    		<div class="col-4">

			    			<!-- Division de Fondo -->
			    			<div class="row fila-fondo mb-4">
			    				<div class="container">
			    					<h5 class="text-uppercase">
			    						<b>
			    							<span class="text-warning fas fa-coins mr-2"></span>
			    							Fondo CICLO: {{fondo.ciclo}}
			    						</b>
			    					</h5>
			    					<div class="d-flex justify-content-center">
			    						<h5 class="text-uppercase">
			    							<a download="RegistroMovimientos.pdf" href="{% url 'pdf_movimientos' %}" class={% if movimientos %} "text-uppercase btn btn-secondary" {% else %} "text-uppercase disabled btn"{% endif %}>
												<span class="fas fa-tasks mr-2"></span>
			    								Ver Registro
			    							</a>
			    						</h5>
			    					</div>
			    					<div class="container" id="saldoDiv">
			    						<h4 class="text-right">Saldo: <b>Q. {{fondo.saldo}}</b></h4>
			    					</div>
			    				</div>
			    			</div>

			    			<!-- Division de Planificacion -->
			    			<div class="row">
			    				<div class="container">
			    					<h5 class="text-uppercase">
			    						<b>
			    							<span class="text-info far fa-list-alt mr-2"></span>
			    							Planificacion
			    						</b>
			    					</h5>
			    					<div class="d-flex justify-content-center">
			    						<h5 class="text-uppercase">
			    							<button class=" {% if planificacion %} btn btn-info {% else %} disabled btn btn-dark{% endif %}btn btn-lg text-uppercase">
												<span class="fas fa-file-download mr-2"></span>
			    								Descargar
			    							</button>
			    						</h5>
			    					</div>
			    				</div>
			    			</div>
			    		</div>
			    	</div>
			    </div>
			</div>
		</div>
	</div>
{% endblock content %}

{% block js_block %}
<script>
    $(document).ready( function () {


    });
</script>
{% endblock js_block %}

comite/templates/comite/integrante_confirm_delete.html
<div class="modal-dialog shadow">
	<div class="modal-content">

		<form method="post">{% csrf_token %}
			<!-- Card Body -->
			<div class="card-body">
							<div class="row no-gutters aling-items-center">
								<div class="col mr-2">
									<div class="container">
										<div class="row">
											<p><span class="fas fa-exclamation-circle text-warning mr-2" style="font-size:26px"></span>¿Está seguro de que quiere borrar: <b>"{{ object }}"</b>?</p>
											<small class="text-justify"><span class="text-danger">
												<span class="fas fa-exclamation text-danger mr-2"></span>Al hacer click en <b>Sí,</b> se eliminara el objeto <b>Integrante</b> y no se podra recuperar..!
											</span></small>
										</div>
									</div>
								</div>
							</div>
			</div>

			<!-- Card Footer -->
			<div class="card-footer">
				<div class="row">
					<div class="col d-flex justify-content-between">
						<button id="delete" class="btn btn-warning text-white" value="">Sí, Estoy Seguro</button>
						<button onclick="return cerrar_modal()" type="submit" class="btn btn-danger">Cancelar</button>
					</div>
				</div>
			</div>
		</form>

	</div>

</div>

		<small class="text-danger">
			{% if form.errors %}
				{% for field in form %}
					{% if field.errors %}
						{% for error in field.errors  %}
							<p>{{field.name}} {{error|escape}}</p>
						{% endfor %}
					{% endif %}
				{% endfor %}

				{% if form.non_field_errors %}
					{% for error in field.errors  %}
							{{error|escape}}
						{% endfor %}
				{% endif %}
			{% endif%}
		</small>

	</div>
</div>

<script>

	// Eliminar con ajax una escuela
	var token = $('input[name=csrfmiddlewaretoken]').val();
	$.ajaxSetup({
		beforeSend: function(xhr, settings) {
			if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))){
				xhr.setRequestHeader("X-CSRFToken", token);
			}
		}
	});

		$("#delete").click(function(e){
			e.preventDefault();
			var id = "{{ object.pk }}";
			var template = "{% url 'eliminar_intengrante' object.pk %}";
			var data = {"id":id};
			data = JSON.stringify(data);

			$.ajax({
                type: "POST",
                url: template,
                data: data,
                beforeSend: function(xhr, settings){
                	$.ajaxSettings.beforeSend(xhr, settings);
                },
                success: function(response){
                    cerrar_modal();
                    location.reload();
                },
                error: function(jqXHR, textStatus, errorThrow){
                    console.log(textStatus, errorThrow);
                    cerrar_modal();
                }
            });

		});
</script>

comite/templates/comite/movimientofondo_form.html
{% load widget_tweaks %}
{% load static %}
<style>
	.new_add{
		border-left: 3px solid #02B012;
		border-bottom: 3px solid #02B012;
	}
	.edit{
		border-left: 3px solid #FF9A23;
	}
</style>
<div class="modal-dialog shadow">
	<div class="modal-content new_add">
		<form method="POST" role="form" class="form-group" id="asignacionForm">{%csrf_token%}
			<div class="card">

				<div class="card-header">
					<h5 class="text-uppercase text-warning">
						<span class="text-warning fas fa-coins mr-2"></span>
						<b>Asiganar Capital al Fondo</b>
					</h5>
				</div>

				<div class="card-body">
					<div class="form-group row">
					    <label for="inputEmail3" class="col-sm-4 col-form-label">Monto a Asignar:</label>
					    <div class="col-sm-7">
					      {% render_field form.valor class+="form-control" placeholder="Monto" %}
					      {% render_field form.tipoMovimiento class+="form-control" %}
					      {% render_field form.ciclo class+="form-control"  %}
					    </div>
					</div>

					<div class="row">
						<div class="col">
							<div class="form-group">
							    {% render_field form.observaciones class+="form-control" rows="4" placeholder="Observaciones de la Asignacion del Fondo" %}
							</div>
						</div>
					</div>
					{{form.fondo}}

					<div class="row">
						<div class="col d-flex justify-content-between">
							<button type="submit" class="btn btn-success" id="guardar">Guardar</button>
							<button onclick="return cerrar_modal()" type="submit" class="btn btn-danger">Cancelar</button>
						</div>
					</div>

				</div>
			</div>
		</form>
	</div>
</div>

<script>
	console.log('Fondo: '+id_fondo)
	var anio = (new Date).getFullYear();
	$('#id_tipoMovimiento').prop("checked", true);
	$('#id_fondo').val(id_fondo);
	$('#id_fondo').hide();
	$('#id_ciclo').val(anio);
	$('#id_tipoMovimiento').hide();
	$('#id_ciclo').hide();
	//$('#id_tipoMovimiento').hide();

		$('#asignacionForm').submit(function(event) {
			/* Act on the event */

			event.preventDefault();
			//alert('Enviaste el integrante')

			// Serializamos la data para enviar el form data
			var serializeData = $(this).serialize();

			// Hacemos el llamado Post con ajax
			$.ajax({
				type: 'POST',
				url: "{% url 'asignar' %}",
				data: serializeData,
				success: function(response){
					cerrar_modal();
					$('#saldoDiv').load(' #saldoDiv');
				},
				error: function(response){
					var title = `<h3 class='Text-danger'><span class="fas fa-exclamation-circle"></span> Error</h3>`;
					mensaje(title, 'Si ve este error es porque existe una asignacion al fondo de este año', 'red');
					cerrar_modal();
				}
			})
		});

</script>